name: yeth-periphery
plugins:
  - name: vyper
  - name: foundry
  - name: etherscan
ethereum:
  default_network: mainnet-fork
  local:
    default_provider: foundry
  mainnet_fork:
    default_provider: foundry
